webapp: feat: delegation as workflow's owner
Madek/madek pull request #298
Opened 2021-01-28 10:41 UTC by michalpodlecki

Closes: #286

2021-01-28 12:27 UTC, eins78 requested changes
the "combined" autocomplete should only give a general "not found" message if there are no results at all – not grouped by type.

<img width="694" alt="Screen Shot 2021-01-28 at 12 38 42" src="https://user-images.githubusercontent.com/134942/106138366-57109980-616c-11eb-9bd2-420ecf995adb.png">

2021-01-28 12:33 UTC, michalpodlecki commented
ok, I'm on it

2021-01-28 14:30 UTC, michalpodlecki commented
@eins78 I've made the solution for what you requested. Please take a look

2021-02-01 15:04 UTC, eins78 approved these changes

2021-02-01 15:35 UTC, merged